version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    rebase-strategy: "auto"
    commit-message:
      prefix: "fix(dependancies)"