version: "2"
services:
  mysql-master:
    image: mysql:8.0
    networks:
      - mynetwork
    volumes:
      - mysql-replica-main:/var/lib/mysql
    command:
      [
        "mysqld",
        "--datadir=/var/lib/mysql",
        "--bind-address=0.0.0.0",
        "--log-bin=bin.log",
        "--server-id=1"
      ]
    environment:
      &mysql-default-environment
      MYSQL_ROOT_PASSWORD: *************
      MYSQL_DATABASE: bazy_danych
      MYSQL_USER: replica
      MYSQL_PASSWORD: Password@123
    ports:
      - "3308:3306"

  mysql-slave:
    image: mysql:8.0
    networks:
      - mynetwork
    volumes:
      - mysql-replica-read:/var/lib/mysql
    command:
      [
        "mysqld",
        "--datadir=/var/lib/mysql",
        "--bind-address=0.0.0.0",
        "--log-bin=bin.log",
        "--server-id=2"
      ]
    environment: *mysql-default-environment
    ports:
      - "3307:3306"

  dbBackup:
    image: fradelg/mysql-cron-backup
    depends_on:
      - mysql-slave
    networks:
      - mynetwork
    restart: always
    volumes:
      - "C:/Users/julia/Documents/adoption_db_backup:/backup"
    environment:
      <<: *mysql-default-environment
      CRON_TIME: 0 0 * * *
      MYSQL_HOST: mysql-slave
      MYSQL_PORT: 3306
      TIMEOUT: 10s
      INIT_BACKUP: 1

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-replica-main:
  mysql-replica-read:
